/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120352-gda18c2a373-20250722"
#endif /* AVUTIL_FFVERSION_H */
